# Generated by Django 2.2.16 on 2022-09-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220908_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Дайте короткое название группы', max_length=200, verbose_name='Название группы'),
        ),
    ]
